### ISSUE TITLE
Cannot import tracing with pip install

### ISSUE THREAD

**Issue by gregmacfarlane** [UDST/activitysim#145] opened 2017-01-11 15:06 UTC
If I install activitysim from pip and run the example, I get

```sh
Traceback (most recent call last):
  File "simulation.py", line 3, in <module>
    from activitysim import tracing
ImportError: cannot import name tracing
```

Installing the development version from my local working copy shows no such problem.

I'm using homebrew python 2.7 on macOS

**Comment by toliwaga** [comment] 2017-01-16 20:33
I am not able to reproduce this. What version of activitysim do you have installed?

What is the output if you type:
`pip list | grep activitysim`

**Comment by e-lo** [comment] 2017-01-16 20:55
I got this error when I had an older version of activitysim installed in addition to the latest and my pythonpath was looking for it in wrong place.  Eliminating the older version from the pip install and just using the clone from github fixed the problem for me (as I recall)

**Comment by bstabler** [comment] 2017-01-16 22:14
This is likely a local configuration issue so I'm closing this for now.

**Closed by bstabler** 2017-01-16 22:14 UTC
